"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.courseRouter = void 0;
var express_1 = require("express");
var course_controller_1 = require("./course.controller");
var auth_middleware_1 = require("../shared/middlewares/auth.middleware");
var multer_config_1 = require("../config/multer.config");
var role_middleware_1 = require("../shared/middlewares/role.middleware");
var router = (0, express_1.Router)();
var authenticateAndCheckRole = [auth_middleware_1.isAuthenticated, (0, multer_config_1.uploadSingle)('image'), (0, role_middleware_1.checkRole)(['ADMIN', 'COACH'])];
router.get('/', auth_middleware_1.isAuthenticated, (0, role_middleware_1.checkRole)(['STUDENT', 'ADMIN', 'COACH']), course_controller_1.courseController.getCourses);
router.get('/:id', auth_middleware_1.isAuthenticated, (0, role_middleware_1.checkRole)(['STUDENT', 'ADMIN', 'COACH']), course_controller_1.courseController.getCourse);
router.post('/', authenticateAndCheckRole, course_controller_1.courseController.createCourse);
router.put('/:id', authenticateAndCheckRole, course_controller_1.courseController.updateCourse);
router.delete('/:id', authenticateAndCheckRole, course_controller_1.courseController.deleteCourse);
//router.get('/', isAuthenticated, courseController.getCourses);
//router.get('/:id', isAuthenticated, courseController.getCourse);
//router.post('/', isAuthenticated, uploadSingle('image'), courseController.createCourse);
exports.courseRouter = router;
